### ISSUE TITLE
Package and publish

### ISSUE THREAD

**Issue by xasx** [xasx/insomnia-plugin-nord-theme#1]
AFAICS, Insomnia plugins are distributed via NPM,

Find out what is necessary to do so and then do so.

**Comment by obahareth** [comment]
@xasx Any update on this? 😄

**Comment by xasx** [comment]
@obahareth I utilized Actions to publish some initial version.

Please feel free to try out and share feedback. Thank you 💮

**Comment by obahareth** [comment]
Nice! I installed `insomnia-plugin-nord-theme` and then `Nord (dark)` and `Nord (light)` showed up in the themes tab and it worked wonderfully!

Thanks @xasx!

**Comment by xasx** [comment]
Thanks @obahareth for feedback.

If you have any ideas for the themes themselves, don't hesitate feedbacking them here 💚
